# ===================================
# ANALYTICS SERVICE - DEV PROFILE
# ===================================

server.port=8087

spring.datasource.url=jdbc:postgresql://localhost:5432/analytics_db
spring.datasource.username=postgres
spring.datasource.password=1230
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
