# ===================================
# SHARED DEV PROFILE
# ===================================

# Logging
logging.level.root=INFO
logging.level.com.capg=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Show SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
