# ===================================
# APPLICATION SERVICE - DEV PROFILE
# ===================================

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/application_db
spring.datasource.username=postgres
spring.datasource.password=1230
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
