# ===================================
# JOB SERVICE - DEV PROFILE
# ===================================

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/jobportal_job_db
spring.datasource.username=postgres
spring.datasource.password=1230
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
