server.port=8085

spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.concurrency=1
spring.rabbitmq.listener.simple.max-concurrency=5

logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.springframework.amqp=DEBUG

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:keshav91900@gmail.com}
spring.mail.password=${MAIL_PASSWORD:vidq lhyg fkiv trbz}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
