# ===================================
# RESUME SERVICE - DEV PROFILE
# ===================================

server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/jobportal_resume
spring.datasource.username=postgres
spring.datasource.password=1230
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
