# ===================================
# SEARCH SERVICE - PROD PROFILE
# ===================================

server.port=8086

spring.datasource.url=jdbc:postgresql://<PROD_DB_HOST>:5432/job_search_db
spring.datasource.username=<PROD_DB_USERNAME>
spring.datasource.password=<PROD_DB_PASSWORD>
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
