server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/jobportal_user_db
spring.datasource.username=postgres
spring.datasource.password=1230
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=admin
spring.security.user.password=admin
spring.jackson.serialization.fail-on-empty-beans=false

jwt.secret=mysecretkeymysecretkeymysecretkey
jwt.expiration=3600000
