# ===================================
# USER SERVICE - DEV PROFILE
# ===================================

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/jobportal_user_db
spring.datasource.username=postgres
spring.datasource.password=1230
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=mysecretkeymysecretkeymysecretkey
jwt.expiration=3600000
